### ISSUE TITLE
Recursos de clase y descargas simultáneas

### ISSUE THREAD

**Issue by mrverns** [Devil64-Dev/platzi-dtool#1]
Estuve probando platzi-dtool con **Ubuntu 18,04 LTS** con WLS en Windows 10 y hasta el momento descarga muy bien los videos de los cursos, pero en el caso de los recursos de clase, que en su mayoría son PDF, no me los descarga, solo descarga archivos html como extra files. 

Por otro lado, solo instalé Ubuntu para utilizar platzi-dtool y estoy recién conociendo su funcionamiento, ¿cómo puedo hacer descargas simultáneas o descargar toda una ruta de aprendizaje?

Gracias por el aporte! Un saludo!

**Comment by Devil64-Dev** [comment]
1: Debido a que hice el programa de manera apresurada todavia no he estudiado como se estructuran los archivos o recursos externes de cada lección es por esa razón que descarga la página web de la lección para poder abrir y descargar los recursos manualmente, espero pronto tener tiempo para implementar esa función.

2. Para descargar una ruta completa, se puede solo pones la url por ejemplo: https://platzi.com/web y te cargara el lista de todos los cursos disponibles y empezara a descar lección por lección cada cursos hasta llegar al último.

3. En cuanto a descargas simultaneas es posible, pero no lo hice ya que mi conexión a Internet es realmente mala y es algo complicado manejar mas de 1 descarga en mi red, pero si tu red es buena, puedo mandarte una actualizacón para que puedas elegir cuantas lecciones quieres descargar al mismo tiempo, de momento el prorgama descarga lección por lección, pero de momento puedes ejecutar el programa 3 veces o mas para descargar diferentes cursos o rutas.

**Comment by mrverns** [comment]
R1. Me puse a revisar con más detención los extra files y me deja ingresar a los html pero no me muestra los enlaces de descarga de los recursos. Adjunto imagen.
![Captura de pantalla 2021-03-26 000155](https://user-images.githubusercontent.com/81399229/112571494-eb8f2500-8dc6-11eb-99c8-64ec277bd42e.png)

R2. Me funcionó, gracias.

R3. Sería genial contar con esa alternativa para ver cuánto me aguanta la conexión.

**Comment by Devil64-Dev** [comment]
Acutalización: Revice y al parecer no es posible de momento descargar los recursos de la lección de forma automatica, se tendra que hacer manual si se necesitan... investigare y si hay alguna forma se integrara la función.
