### ISSUE TITLE
Error al descargar cursos Windows WSL Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Jjaraa** [Devil64-Dev/platzi-dtool#2]
Al intentar realizar una descarga de cualquier curso/escuela aparece este error luego de descargar el html, uso windows 10 con WSL de ubuntu 20.04 LTS, tengo el mismo WSL en un computador de escritorio también con windows 10 y funciona perfecto. Están instalados los módulos solicitados en readme.md y todas las dependencias solicitadas.
Probe cambiando el directorio del curso, limpiando el directorio, cambiando las cookies, clonando el proyecto en otro directorio y el error persiste.

EDIT: el mensaje de error es de IndexError: list index out of range

Codigo de error:
Traceback (most recent call last):
  File "../platzi-dtool/platzi-dtool.py", line 78, in <module>
    __main__()
  File "../platzi-dtool/platzi-dtool.py", line 66, in __main__
    scraper.init()
  File "/home/jjaraa/platzi-dtool/utils/extractor/scraper.py", line 54, in init
    scrape_course("", response[1], response[0])
  File "/home/jjaraa/platzi-dtool/utils/extractor/scraper.py", line 220, in scrape_course
    l_url = lesson.xpath('a[@class="MaterialItem-anchor"]'

**Comment by DcOscar** [comment]
Tengo el mismo problema, igualmente estoy corriendo ubuntu 20.04 LTS mediante WSL en windows 10. adjunto imagen
![image](https://user-images.githubusercontent.com/43186229/112671224-af98a600-8e40-11eb-869b-53e3a0411668.png)

**Comment by Devil64-Dev** [comment]
El problema puede ser con la autenticacón, revisen si tienen el archivo cookies.txt, otro posible factor de error puede ser que el la lección aún no esta disponible, lo arreglare enseguida.

**Comment by DcOscar** [comment]
Si tengo el archivo cookies.txt, de hecho durante la mañana me estaba descargando bien el mismo curso que se visualiza, hasta que en un momento terminó repentinamente y luego no me deja descargar ningún curso

**Comment by Devil64-Dev** [comment]
Revisa si en el navegador tienes la sesión activa aún, de ser así intenta actualizar el archivo cookies.txt

**Comment by Jjaraa** [comment]
Solucionado, el problema era por exportar las cookies de la extensión cookies.txt, utilizando la extensión export cookies funcionó perfecto. Gracias por la respuesta!

**Comment by estebanardila57** [comment]
hay algun tutorial en windows para poder hacer funcionar esto en windows creo que estoy haciendo algunos pasos mal

**Comment by Jjaraa** [comment]
> hay algun tutorial en windows para poder hacer funcionar esto en windows creo que estoy haciendo algunos pasos mal

La issue está cerrada, crea una nueva con tu problema específico para poder ayudarte.
