### ISSUE TITLE
Algún tutorial para hacer funcionar la herramienta para windows ?

### ISSUE THREAD

**Issue by estebanardila57** [Devil64-Dev/platzi-dtool#3]
Perdón , no es como tal un accdiente , pero e querido hacerla funcionar pero no se  muy bien como hacer este proceso para windows

**Comment by Devil64-Dev** [comment]
Seria algo dificil para mi decirte como hacer funcionar el script en Windows ya que todo el proceso de instalación y de pruebas lo hice en Linux.

Para hacer funcionar el programa en Windows es posible aunque tendrias que saber algo basíco de Python y Linux ya que los comandos usados en el programa son programas comúnes en entors Unix-like pero no en Windows así que principalmente por esa razón el programa no funcionara en Windows, ademas de que las herramientas externas usadas para descargar los cursos no se ejecutan de la misma manera que en Windows.

**Comment by Devil64-Dev** [comment]
Si quieres soporte para Windows, como lo dije en el comentario del otro hilo, estoy trabajando en una versión que se adapte en Windows sin necesidad de hacer modificaciónes severas en el código.

**Comment by estebanardila57** [comment]
![image](https://user-images.githubusercontent.com/43124834/112741761-f32d0600-8f4d-11eb-8754-5e4da7d01f1e.png)
 Es que el problema soy yo , soy culpable , :( pues tenia todo instalado en windows para que funcionase pero no logro hacer funcionar los demás comandos en la consola de linux

**Comment by Devil64-Dev** [comment]
1. Es ubuntu así que el comando sudo pacman no funcionara, toda la instalación hasla con sudo apt-get
2. Antes de cualquier instalación ejecuta el comando `sudo apt-get update && sudo apt-get upgrade`

**Comment by estebanardila57** [comment]
Listo , muchas gracias ya acabó de intalarse todo lo necesario , muchas gracias por toda la ayuda, no estoy tan familiarizado con linux pero ahi , paso a paso voy comprendiendo, ahora la cuestión es que tengo la carpeta donde esta platzi-dtool dentro de mi disco local C en el sistema adentro esta el archivo de cookie exportado desde la extensión get cookies.txt (esta esta bien ? , causa problemas , o mejor me paso a la export coockies de Mozilla) 
Intento seguir la guía pero no logro hacer coincidir la ruta para poder acceder,  presiono ls para intentar encontrar la ruta pero no me sale absolutamente nada , o donde la debo ubicar para poder acceder al archivo, mil disculpas por las molestias
![image](https://user-images.githubusercontent.com/43124834/112743378-62115b80-8f5c-11eb-85ff-e8fc4eb28173.png)
![image](https://user-images.githubusercontent.com/43124834/112743387-7bb2a300-8f5c-11eb-8945-21a41114c628.png)

**Comment by Devil64-Dev** [comment]
En un momento te explico que hacer para que que funcione sin problemas.

**Comment by estebanardila57** [comment]
ok muchas , muchas gracias nuevamente por todo

**Comment by Devil64-Dev** [comment]
Me disculpo por la demora, ya que también soy nuevo en WSL, si todavia tienes animo de intentarlo, aquí hay unas guias de miscrosoft que explican muy bien como usar correctamente WSL.
1. Instalación de WSL 2: [WSL Install guide](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
2. Como monstar discos: [Mount disk in WSL](https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk)

Para montar el disco virtual tendras que actualizar a WSL 2, ya que la instalación por defecto no tiene la utilidad de montar el disco donde se encuentra el subsitema linux.

Como ya habilitaste e instalaste una distribución tendras, te dire que hacer para que no tengas que volver a descargar todo.
1. Actualiza a WSL 2, la arquitectura de tu computador es de 64 bits (todas las computadoras modernas son de 64bits), instala el siguiente archivo: [WSL 2 Update](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi), no te preocupes es un enlace proporcionado por Miscrosoft.

Todos los comandos a apartir de ahora los ejecutaras en Windows PowerShell:
  1. Cambia la versión de WSL a la versión 2, ejecuta el comando `wsl --set-default-version 2`
  2. Actualiza la versión de WSL en tu distribución, para este paso primero deberas obtener el nombre de tu distribución y verificar
      si la versión de WSL es diferente a `2`, para esto ejecuta `wsl --list --verbose`, te dara una salida similar a esta:
                                            NAME                   STATE           VERSION
                                          Ubuntu-20.04    Stopped              2
     si en el campo versión el valor es 2 no debes hacer nada mas, si es uno ejecuta el siguiente comando:
     `wsl --set-version "distro_name" 2`, reemplazas `distro_name` con el valor del campo "NAME" en mi caso el comando quedaria:
     `wsl --set-version "ubuntu-20.04" 2`. Si al ejecutar el comando despues de un tiempo corto obverbas que esta detenido
     presiona la tecla **Intro o Enter**.

Una vez todo este completo, ejecutas tu distro Linux como lo haces normalmente, y dentro de la distro ejecutas los siguientes comandos:
  Antes de ejecutar los comandos deberas cambiar al super usuario, para ello primero debes actualizar la contraseña de super usuario, dentro de tu distro ejecuta: `sudo passwd` y escribes una nueva contraseña, luego ejecutas: `su` despues de pedira la contraseña que escribieste antes.
 Cuando estes en modo super usuario veras que el simbolo que se encuentra antes del cursor cambio de `$` a `#`, si toda va bien ya puedes seguir.
    1. Entrar al disco donde esta instalado Windows, ejecuta: `cd /mnt/c`
    2. Lista los directorios: `ls` deberas ver alguna carpeta llamada *Documents and Settings* o algo similar, entramos a la carpeta
        con el comando `cd nombre_carpeta` cambia nombre carpeta por la carptea a la que quieres entrar en mi caso seria:
        `cd Documents and Settings` ya que aquí es donde estan mis carpetas de Usuario.
   3. Dentro de la carpeta *Documents and Settings*,  lsita los archivos para identificar tu carpeta de usuario (tu carpeta de usuaio deberia serte algo familiar, tendra tu nombre o una parte de el), entras a la carpeta de tu usuario `cd user_name`, cambia user name por el nombre de tu usuario.
   4. Una vez dentro de la carptea de tu usuario ya podras encontrar las carpteas que usas normalmente pero en Ingles *Downloads*, *Documents*.
   5. Ingresa a una carpeta donde sea fácil almenar los cursos, en mi caso para el ejemplo usare la carpeta de descargas `cd Downloads` una vez dentro ejecutamos `git clone https://github.com/Devil64-Dev/platzi-dtool` para descargar el programa. Si quieres saltarte este paso simplement mueve la carpeta del programa a una de tus carpetas de usuario como *Descargas o Documentos* y listo.
   6. Desde aquí solo siguie la instalación normal de los modulos y programas desde la distro en WSL.

**Comment by estebanardila57** [comment]
Hola , muchas gracias por responder , hice todos los pasos que me indicaste  y quede ya en el paso 5 , pero queria preguntarte si yo quiero para evitarme tantas rutas largas puedo dejar la carpeta platzi-dtool ali en el c cierto , ya la puedo ver entonces no habria problema ? , y otra pregunta yo instale todos los modulos que estaban alli en la documentacion 
![image](https://user-images.githubusercontent.com/43124834/112757644-420b8780-8fb0-11eb-9004-27ce04b32323.png)  , los que muestro entonces haber si logro entender , disculpame si ya me lo indicaste pero falta poco para que todo me quede claro te lo juro :) , entonces tengo que instalar los módulos pero dentro de la ruta  que muestro alli en la terminal , o si ya los instale aparte no los tengo que volver a instalar  mil disculpas , y aun me faltan algunas dudas con la descarga pero voy a hacer todo  lo posible para que funcione , no me rindo, muchas gracias nuevamentepor toda la ayuda
![image](https://user-images.githubusercontent.com/43124834/112757699-826b0580-8fb0-11eb-8d4d-48a7943d0e2d.png)

**Comment by Devil64-Dev** [comment]
De acuerdo, deberás volver a instalar los módulos Python de nuevo, ya que cuando los instalaste antes, se instalaron para el usuario normal, as de cuenta cuando instalas un programa en Windows solo para un usuario, para el resto no queda, entonces tienes que volver a instalarlo, de ese modo vuelve a instalar los módulos y listo todo funcionara bien, asegúrate que estés como súper usuario 'root' deberías ver "#" antes del cursor, si es así procede a instalar los módulos de nuevo. 

Te recomiendo que no ejecutes el script en la misma carpeta donde se encuentra ese, ejecútalo en una diferente, por ejemplo.
Crea una nueva carpeta y entra en ella, luego invoca el script desde allí con un comando similar a este: `../platzi-dtool/platzi-dtool.py`.

Lo digo por comodidad pero puedes hacerlo como mejor te parezca.

**Comment by estebanardila57** [comment]
Listo ok , nuevamente muchas gracias decidi instalarlo alli mismo  porque tenia algo de miedo de que algo sacara error despues del avance que habia hecho 
Ejectue la linea pip3 install requests para instalar este modulo y esto me arrojo Requirement already satisfied: colorama in /usr/lib/python3/dist-packages
Ejecute la linea pip3 install lxml y esto arrojo una instalacion
Ejecute esta liena pip3 install colorama   Requirement already satisfied: colorama in /usr/lib/python3/dist-packages   

Segun lo anterior estamos bien ? o hay algo que falta o todo mal :( ?

![image](https://user-images.githubusercontent.com/43124834/112758416-ec38de80-8fb3-11eb-8b61-4c11202dd047.png)

**Comment by Devil64-Dev** [comment]
Excelente todo esta listo, si no hay nada en rojo todo esta perfecto.

**Comment by estebanardila57** [comment]
ok muchas gracias  :D gracias gracias , ahora tengo unas ultimas preguntas 
1.primero esta: sobre las cookies,...., para obtener el archivo el archivo de las cookies recomiendas getcookies.txt(extension para chrome)
o mas bien export cookies la extension para mozilla

**Comment by Devil64-Dev** [comment]
Recomiendo Export Cookies de Mozilla ya que hice las pruebas con ella, pero si te funciona la extensión de Chrome, entonces no hay problema.

Pero si quieres usar la que uso aquí te dejo el link para en Chrome: [Export Cookies Chrome](https://chrome.google.com/webstore/detail/export-cookies/gnkljdjnepojcjhhaoledinfjmampdcd)

**Comment by estebanardila57** [comment]
Ok si es que retiraron el export cookies de crhome pero tratare con ambos , estoy siguiendo el video guia y en el video se muestra una ruta PlatziCourses pero trato de acceder pero este directorio no corresponde 
![image](https://user-images.githubusercontent.com/43124834/112759745-02e23400-8fba-11eb-8b24-cdfd1b7b699b.png)     perdoname si la pregunta es bastante tonta solo queiro descaergar un curso no toda una ruta de aprendizaje completa

**Comment by Devil64-Dev** [comment]
De acuerdo te voy explicar, PlatziCourse es una carpeta que cree para hacer la demostración en el video, así que no importa.
Ya estas en la carpeta del proyecto para ejecutar el archivo solo tienes que escribir `./platzi-dtool` y listo.

**Comment by estebanardila57** [comment]
![image](https://user-images.githubusercontent.com/43124834/112761377-a33b5700-8fc0-11eb-983d-3ad02e9b1324.png)
Eres el mejor creo que ya lo tengo , esto empezo a funcionar a descargar espero hasta que termine y te comento muchas muchas gracias por todo , eres un Amo y señor <3 ya te agracedí varias veces sobre esto pero mil y mil gracias

**Comment by Devil64-Dev** [comment]
De acuerdo, espero que te funcione bien, recuerda estar actualizando el archivo cookies.txt ya que después de algún tiempo deja de ser valido. Como última recomendación y si tienes un internet mayor a 2MB puedes ejecutar el programa varias veces, para que así puedas aprovechar el la máxima velocidad de tu red. No se si WSL te deja abrir mas de una terminal si es así y quieres descargar mas de un curso o ruta a la vez puedes volver descargar el programa en otra ubicación diferente y lo ejecutas y copiar el archivo cookies.txt y lo ejecutas de ese modo te rendirá mas.

**Comment by estebanardila57** [comment]
Disculpame antes unas ultimas preguntas

1. Si se me llega a cerrar la consola y no terminó de descargar el curso , al intentarlo volver a  hacer , el retoma desde el mismo punto (si no se ha movido la carpeta del curso claro esta) o vuelve a comenzar 
2. Si quiero descargar los video es 720 p es posible o el descarga la calidad mas alta 
3. Eres un Dios , muchas gracias

**Comment by Devil64-Dev** [comment]
1. No te preocupes, si no mueves la carpeta o no cambias el nombre no importa si cancelas el programa si lo vuelves a ejecutar retomara la descarga desde donde estaba anteriormente.

2. Siempre descargara la mejor calidad, ya que en algunos videos solo hay 1080p o 720p por eso lo hice de ese modo, pero investigare y si hay posibilidad integrare la forma de que puedes elegir la calidad del video por ti mismo.

3. Gracias por la gratitud, me gusta mucho ayudar así no te preocupes, si tienes de nuevo un problema avísame que tan pronto puede te responderé.

**Comment by JeanCarlosDEV17** [comment]
amigo esta muy buena tu idea ojala puedas añadir una opcion para darle una pausa  o un temporizador para modular las descargas por que platzi puede llegar a detectarlo y banear la cuenta

**Comment by Devil64-Dev** [comment]
Hola @JeanCarlosDEV17 la característica que acabas de comentar se integrara junto con otras en la próxima gran actualización que estoy preparando. Si tienes mas sugerencias puedes abrir un nuevo hilo para hablar de ello, ya que este se encuentra cerrado.
