### ISSUE TITLE
sugerencias  a esta herramienta,

### ISSUE THREAD

**Issue by JeanCarlosDEV17** [Devil64-Dev/platzi-dtool#4]
hola bro muy buena tu herramienta te agradezco que la compartas, mi energia electrica falla en las tardes y noches lo cual me deja sin internet por un rato la planta solo cubre el cuarto de mis padres, seria muy interesante añadirle ciertas características al comportamiento del script solo seria meterle mano  a la clase download_video y modificar el comando para añadir estas características y como recibirlas como parámetros, sea en txt o algo asi
- Ver el porcentaje de descarga por video y general de un curso
- cuando exista un error de descarga que se guarde en un fichero txt  como un log y asi poder saber  que revisar para descargar manualmente
- poder regular la frecuencia de descarga, añadir un tiempo de pausa para evitar baneos de cuenta
- capacidad para descargar los subtitulos 
- descargar en maxima calidad o elegir la calidad de la descarga
-  seleccionar la velocidad maxima de la descarga

**Comment by JeanCarlosDEV17** [comment]
posdata eres una maquina, yo tenia mi script basado en el de jesus igual pero nada que ver con tu trabajo

**Comment by JeanCarlosDEV17** [comment]
> hola bro muy buena tu herramienta te agradezco que la compartas, mi energia electrica falla en las tardes y noches lo cual me deja sin internet por un rato la planta solo cubre el cuarto de mis padres, seria muy interesante añadirle ciertas características al comportamiento del script solo seria meterle mano a la clase download_video y modificar el comando para añadir estas características y como recibirlas como parámetros, sea en txt o algo asi
> 
> * Ver el porcentaje de descarga por video y general de un curso
> * cuando exista un error de descarga que se guarde en un fichero txt  como un log y asi poder saber  que revisar para descargar manualmente
> * poder regular la frecuencia de descarga, añadir un tiempo de pausa para evitar baneos de cuenta
> * capacidad para descargar los subtitulos
> * descargar en maxima calidad o elegir la calidad de la descarga
> * seleccionar la velocidad maxima de la descarga

**Comment by JeanCarlosDEV17** [comment]
otra sugerencia al usar la herramienta seria bueno que los videos fueran consecutivos por ejemplo si una seccion de un curso empieza en 1 y termina en 5 la siguiente seccion empieza en 6 y termina en 8 y la siguiente en 9 y termina en 15 
 [LN] - [LESSON_NAME] que el  [LN]  sea conscutivo y solo se reinicie al cambiar de curso, dado que los numeros en las clases de platzi son consecutivas

**Comment by Devil64-Dev** [comment]
Hola, debido a que existe mas de un usuario que esta usando la herramienta, hacer el cambio que propones  seria muy drástico ya que si estaba descargando algún cursos y pausa la descarga y actualiza el proyecto a una versión que contenga el cambio que indicas, se tendrán que volver a descargar los videos, aunque se podría parchar para que no suceda, pero de momento no se hará por respeto a los demás usuarios.

**Comment by JeanCarlosDEV17** [comment]
gracias intentare modificarlo yo, entiendo perfectamente lo que dices
